"""Database engine factory — PostgreSQL or DuckDB."""

from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

from src.config.settings import settings

_engine = None
_SessionLocal = None


def _patch_duckdb_types(engine):
    """Monkey-patch DuckDB dialect to fix SERIAL/BIGSERIAL and IDENTITY.

    DuckDB 1.5 doesn't support GENERATED BY DEFAULT AS IDENTITY.
    We replace PG SERIAL/BIGSERIAL with plain BIGINT/INTEGER +
    DEFAULT nextval('sequence_name').  Sequences are created separately
    by scripts/init_db.py before create_all.
    """
    from sqlalchemy.dialects.postgresql.base import PGDDLCompiler

    _original_get_colspec = PGDDLCompiler.get_column_specification

    def _patched_get_colspec(self, column, **kwargs):
        result = _original_get_colspec(self, column, **kwargs)
        # Replace PG SERIAL types → BIGINT/INTEGER (sequences created separately)
        result = result.replace(" BIGSERIAL ", " BIGINT ")
        result = result.replace(" SERIAL ", " INTEGER ")
        # Replace IDENTITY clause (if any) → plain type
        result = result.replace(" GENERATED BY DEFAULT AS IDENTITY", "")
        # For autoincrement PK, add sequence default
        if (
            column.primary_key
            and column is column.table._autoincrement_column
            and column.autoincrement
        ):
            table_name = column.table.name
            seq_name = f"seq_{table_name}_id"
            result = result.replace(
                "BIGINT NOT NULL",
                f"BIGINT DEFAULT nextval('{seq_name}') NOT NULL",
            )
            result = result.replace(
                "INTEGER NOT NULL",
                f"INTEGER DEFAULT nextval('{seq_name}') NOT NULL",
            )
        return result

    PGDDLCompiler.get_column_specification = _patched_get_colspec


def get_engine():
    """Get or create the SQLAlchemy engine (singleton)."""
    global _engine
    if _engine is None:
        if settings.db_backend == "duckdb":
            settings.duckdb_path.parent.mkdir(parents=True, exist_ok=True)
            _engine = create_engine(
                f"duckdb:///{settings.duckdb_path}",
                echo=False,
            )
            _patch_duckdb_types(_engine)
        else:
            _engine = create_engine(
                settings.db.dsn,
                pool_size=5,
                max_overflow=10,
                pool_pre_ping=True,
                pool_recycle=3600,
                echo=False,
                connect_args={"connect_timeout": 10},
            )
    return _engine


def get_session() -> Session:
    """Get a new database session."""
    global _SessionLocal
    if _SessionLocal is None:
        _SessionLocal = sessionmaker(bind=get_engine())
    return _SessionLocal()


def dispose_engine():
    """Dispose the engine (useful for tests)."""
    global _engine, _SessionLocal
    if _engine:
        _engine.dispose()
    _engine = None
    _SessionLocal = None
