"""股票技术面因子(专业版) RawStkFactorPro — auto-generated from stk_factor_pro."""

from __future__ import annotations

from typing import Optional

from sqlalchemy import BigInteger, Float, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import Base, TimestampMixin


class RawStkFactorPro(TimestampMixin, Base):
    """股票技术面因子 — 专业版 (stk_factor_pro)."""
    __tablename__ = "raw_stk_factor_pro"
    __table_args__ = (
        UniqueConstraint("ts_code", "trade_date", name="uq_raw_stk_factor_pro_code_date"),
        {"comment": "股票技术面因子(专业版) — 原始数据"},
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    trade_date: Mapped[str] = mapped_column(String(8), nullable=False, index=True)
    open: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    open_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    open_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    high: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    high_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    high_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    low: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    low_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    low_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    close: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    close_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    close_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pre_close: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    change: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pct_chg: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    vol: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    amount: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    turnover_rate: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    turnover_rate_f: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    volume_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pe: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pe_ttm: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pb: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ps: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ps_ttm: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dv_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dv_ttm: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    total_share: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    float_share: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    free_share: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    total_mv: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    circ_mv: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    adj_factor: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    asi_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    asi_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    asi_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    asit_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    asit_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    asit_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    atr_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    atr_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    atr_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bbi_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bbi_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bbi_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias1_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias1_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias1_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias2_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias2_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias2_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias3_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias3_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bias3_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_lower_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_lower_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_lower_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_mid_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_mid_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_mid_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_upper_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_upper_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    boll_upper_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    brar_ar_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    brar_ar_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    brar_ar_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    brar_br_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    brar_br_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    brar_br_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cci_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cci_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cci_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cr_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cr_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cr_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dfma_dif_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dfma_dif_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dfma_dif_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dfma_difma_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dfma_difma_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dfma_difma_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_adx_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_adx_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_adx_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_adxr_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_adxr_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_adxr_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_mdi_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_mdi_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_mdi_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_pdi_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_pdi_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dmi_pdi_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    downdays: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    updays: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dpo_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dpo_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    dpo_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    madpo_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    madpo_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    madpo_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_10: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_250: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_30: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_5: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_60: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_bfq_90: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_10: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_250: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_30: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_5: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_60: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_hfq_90: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_10: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_250: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_30: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_5: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_60: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_qfq_90: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    emv_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    emv_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    emv_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    maemv_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    maemv_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    maemv_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expma_12_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expma_12_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expma_12_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expma_50_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expma_50_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expma_50_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_d_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_d_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_d_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_k_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_k_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kdj_k_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_down_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_down_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_down_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_mid_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_mid_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_mid_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_upper_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_upper_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ktn_upper_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    lowdays: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    topdays: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_10: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_250: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_30: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_5: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_60: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_bfq_90: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_10: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_250: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_30: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_5: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_60: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_hfq_90: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_10: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_250: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_30: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_5: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_60: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_qfq_90: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_dea_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_dea_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_dea_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_dif_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_dif_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_dif_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mass_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mass_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mass_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_mass_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_mass_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ma_mass_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mfi_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mfi_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mfi_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mtm_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mtm_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mtm_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mtmma_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mtmma_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mtmma_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    obv_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    obv_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    obv_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    psy_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    psy_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    psy_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    psyma_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    psyma_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    psyma_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    roc_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    roc_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    roc_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    maroc_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    maroc_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    maroc_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_bfq_12: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_bfq_24: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_bfq_6: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_hfq_12: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_hfq_24: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_hfq_6: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_qfq_12: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_qfq_24: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_qfq_6: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_down_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_down_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_down_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_mid_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_mid_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_mid_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_up_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_up_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    taq_up_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trix_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trix_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trix_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trma_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trma_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trma_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    vr_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    vr_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    vr_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    wr_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    wr_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    wr_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    wr1_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    wr1_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    wr1_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td1_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td1_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td1_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td2_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td2_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td2_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td3_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td3_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td3_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td4_bfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td4_hfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    xsii_td4_qfq: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    raw_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class RawStkNineturn(TimestampMixin, Base):
    """神奇九转 — TD序列反转指标 (stk_nineturn)."""
    __tablename__ = "raw_stk_nineturn"
    __table_args__ = (
        UniqueConstraint("ts_code", "trade_date", name="uq_raw_stk_nineturn_code_date"),
        {"comment": "神奇九转 — TD序列反转指标"},
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    trade_date: Mapped[str] = mapped_column(String(10), nullable=False, index=True)  # YYYY-MM-DD
    freq: Mapped[str] = mapped_column(String(8), nullable=False)
    open: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    high: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    low: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    close: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    vol: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    amount: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    up_count: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    down_count: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    nine_up_turn: Mapped[Optional[str]] = mapped_column(String(8), nullable=True)
    nine_down_turn: Mapped[Optional[str]] = mapped_column(String(8), nullable=True)
    raw_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
